# Generated by Django 5.1.3 on 2024-12-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimonal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonal',
            new_name='Testimonial',
        ),
    ]
